#!/bin/sh -e

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 REPO VERSION" >&2
  exit 0
else
  REPO=$1
  VERSION=$2
fi

BASE_URL=https://github.com/esplinux-$REPO

echo "# INDEX for $REPO"

# make
curl -L $BASE_URL/make/releases/download/$VERSION/version.txt
