version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.9
    environment:
      VERSION: "bootstrap"
      ESPBUILD_VERSION: "0.01"
      GHR_VERSION: "v0.12.1"
    steps:
      - checkout
      - run: apk add ca-certificates curl go git build-base
      - run:
          name: Build
          command: |
            curl -LO https://github.com/esplinux/espbuild/releases/download/$ESPBUILD_VERSION/espbuild-static.tar.gz
            tar xf espbuild-static.tar.gz
            mkdir /package
            bin/build_index gnu $VERSION > /package/INDEX.txt
            go mod init .
            go get github.com/tcnksm/ghr@$GHR_VERSION
            ~/go/bin/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /package

workflows:
  build:
    jobs:
      - build
